spring:
  kafka:
    bootstrap:
      servers: 192.168.174.132:9092
    topic:
      log-info
    group:
      id: log-info-group
    max:
      poll:
        records: 500
    key:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer

  es:
    hostname: 192.168.174.132
    port: 9200
    schema: http
    username: elastic
    passwd: elastic
    index: dbAudit
