spring:
  kafka:
    bootstrap:
      servers: 192.168.0.128:9092
    bootstrap-servers: 192.168.0.128:9092
    topic:
#      log-info-db
      log-info-host
    group:
      id: log-info-group1
    max:
      poll:
        records: 3000
    key:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer

  es:
    hostname: 192.168.0.128
    port: 9200
    schema: http
    username: elastic
    passwd: 971122
    index: databaseaudit-hy

  inner:
    consumer: true  # 发送kafka消息时将其改为 false

syslog:
  producer:
    host: 127.0.0.1
    port: 5144
    protocol: UDP

  consumer:
    host: 127.0.0.1
    port: 5144
    protocol: UDP